name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: jurre-vlas
          password: ${{ secrets.GH_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: WebApplication1
          push: true
          tags: ghcr.io/jurre-vlas/eindopdrachtcdn:latest
