name: Docker Image CI 

on: 
  push


jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and push the image
      run: |
       docker login --username jurre-vlas --password ${{ secret.GH_PAT}} ghcr.io
        docker build . --tag ghcr.io/jurre-vlas/cdn-eindopdrachtcdn:latest
        docker push ghcr.io/jurre-vlas/eindopdrachtcdn:latest
